//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validation.hitsp.nist.gov", ConfigurationName="NistRemoteValidator.ValidationWebServicePortType")]
    public interface ValidationWebServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:validateDocument", ReplyAction="urn:validateDocumentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentResponse validateDocument(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation getAvailableValidations is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAvailableValidations", ReplyAction="urn:getAvailableValidationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsResponse getAvailableValidations(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validation.hitsp.nist.gov/xsd")]
    public partial class WSValidationResults : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WSIndividualValidationResult[] issueField;
        
        private string validationDateField;
        
        private bool validationTestField;
        
        private bool validationTestFieldSpecified;
        
        private string validationTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("issue", IsNullable=true, Order=0)]
        public WSIndividualValidationResult[] issue {
            get {
                return this.issueField;
            }
            set {
                this.issueField = value;
                this.RaisePropertyChanged("issue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string validationDate {
            get {
                return this.validationDateField;
            }
            set {
                this.validationDateField = value;
                this.RaisePropertyChanged("validationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool validationTest {
            get {
                return this.validationTestField;
            }
            set {
                this.validationTestField = value;
                this.RaisePropertyChanged("validationTest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validationTestSpecified {
            get {
                return this.validationTestFieldSpecified;
            }
            set {
                this.validationTestFieldSpecified = value;
                this.RaisePropertyChanged("validationTestSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string validationTime {
            get {
                return this.validationTimeField;
            }
            set {
                this.validationTimeField = value;
                this.RaisePropertyChanged("validationTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validation.hitsp.nist.gov/xsd")]
    public partial class WSIndividualValidationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contextField;
        
        private string messageField;
        
        private string severityField;
        
        private string specificationField;
        
        private string testField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string specification {
            get {
                return this.specificationField;
            }
            set {
                this.specificationField = value;
                this.RaisePropertyChanged("specification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://validation.hitsp.nist.gov/xsd")]
    public partial class WSSpecification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string nameField;
        
        private string specificationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string specificationId {
            get {
                return this.specificationIdField;
            }
            set {
                this.specificationIdField = value;
                this.RaisePropertyChanged("specificationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocument", WrapperNamespace="http://validation.hitsp.nist.gov", IsWrapped=true)]
    public partial class validateDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validation.hitsp.nist.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string specificationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validation.hitsp.nist.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string document;
        
        public validateDocumentRequest() {
        }
        
        public validateDocumentRequest(string specificationId, string document) {
            this.specificationId = specificationId;
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateDocumentResponse", WrapperNamespace="http://validation.hitsp.nist.gov", IsWrapped=true)]
    public partial class validateDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validation.hitsp.nist.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSValidationResults @return;
        
        public validateDocumentResponse() {
        }
        
        public validateDocumentResponse(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSValidationResults @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAvailableValidationsRequest {
        
        public getAvailableValidationsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAvailableValidationsResponse", WrapperNamespace="http://validation.hitsp.nist.gov", IsWrapped=true)]
    public partial class getAvailableValidationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://validation.hitsp.nist.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSSpecification[] @return;
        
        public getAvailableValidationsResponse() {
        }
        
        public getAvailableValidationsResponse(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSSpecification[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidationWebServicePortTypeChannel : LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationWebServicePortTypeClient : System.ServiceModel.ClientBase<LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType>, LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType {
        
        public ValidationWebServicePortTypeClient() {
        }
        
        public ValidationWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentResponse LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType.validateDocument(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentRequest request) {
            return base.Channel.validateDocument(request);
        }
        
        public LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSValidationResults validateDocument(string specificationId, string document) {
            LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentRequest inValue = new LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentRequest();
            inValue.specificationId = specificationId;
            inValue.document = document;
            LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.validateDocumentResponse retVal = ((LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType)(this)).validateDocument(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsResponse LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType.getAvailableValidations(LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsRequest request) {
            return base.Channel.getAvailableValidations(request);
        }
        
        public LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.WSSpecification[] getAvailableValidations() {
            LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsRequest inValue = new LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsRequest();
            LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.getAvailableValidationsResponse retVal = ((LantanaGroup.TestDataGenerator.Shared.NistRemoteValidator.ValidationWebServicePortType)(this)).getAvailableValidations(inValue);
            return retVal.@return;
        }
    }
}
